const vocab = [
  { key: "vocab-1", type: "vocab", word: "Abate", meaning: "to become less intense or widespread", meaningKeywords: ["less", "reduce", "decrease"], synonym: "diminish", antonym: "intensify" },
  { key: "vocab-2", type: "vocab", word: "Adept", meaning: "highly skilled or proficient", meaningKeywords: ["skilled", "proficient", "expert"], synonym: "skilled", antonym: "clumsy" },
  { key: "vocab-3", type: "vocab", word: "Amiable", meaning: "friendly and pleasant", meaningKeywords: ["friendly", "pleasant", "warm"], synonym: "cordial", antonym: "hostile" },
  { key: "vocab-4", type: "vocab", word: "Arduous", meaning: "requiring great effort", meaningKeywords: ["difficult", "effort", "hard"], synonym: "strenuous", antonym: "easy" },
  { key: "vocab-5", type: "vocab", word: "Astute", meaning: "having sharp judgment", meaningKeywords: ["clever", "shrewd", "judgment"], synonym: "shrewd", antonym: "naive" },
  { key: "vocab-6", type: "vocab", word: "Benevolent", meaning: "well meaning and kindly", meaningKeywords: ["kind", "helpful", "well meaning"], synonym: "kindhearted", antonym: "malevolent" },
  { key: "vocab-7", type: "vocab", word: "Candid", meaning: "truthful and straightforward", meaningKeywords: ["truthful", "frank", "straightforward"], synonym: "frank", antonym: "deceptive" },
  { key: "vocab-8", type: "vocab", word: "Coherent", meaning: "logical and consistent", meaningKeywords: ["logical", "consistent", "clear"], synonym: "logical", antonym: "confused" },
  { key: "vocab-9", type: "vocab", word: "Diligent", meaning: "careful and hardworking", meaningKeywords: ["hardworking", "careful", "steady"], synonym: "industrious", antonym: "lazy" },
  { key: "vocab-10", type: "vocab", word: "Eloquent", meaning: "fluent and persuasive in speaking", meaningKeywords: ["fluent", "persuasive", "expressive"], synonym: "articulate", antonym: "inarticulate" },
  { key: "vocab-11", type: "vocab", word: "Empathy", meaning: "the ability to understand another person's feelings", meaningKeywords: ["understand", "feelings", "others"], synonym: "compassion", antonym: "indifference" },
  { key: "vocab-12", type: "vocab", word: "Endeavor", meaning: "an earnest attempt", meaningKeywords: ["attempt", "effort", "try"], synonym: "effort", antonym: "idleness" },
  { key: "vocab-13", type: "vocab", word: "Fortify", meaning: "to strengthen or secure", meaningKeywords: ["strengthen", "secure", "reinforce"], synonym: "reinforce", antonym: "weaken" },
  { key: "vocab-14", type: "vocab", word: "Frugal", meaning: "careful about spending resources", meaningKeywords: ["economical", "careful", "saving"], synonym: "economical", antonym: "wasteful" },
  { key: "vocab-15", type: "vocab", word: "Harmony", meaning: "agreement or peaceful coexistence", meaningKeywords: ["peace", "agreement", "balance"], synonym: "accord", antonym: "conflict" },
  { key: "vocab-16", type: "vocab", word: "Impeccable", meaning: "flawless or faultless", meaningKeywords: ["flawless", "perfect", "faultless"], synonym: "faultless", antonym: "imperfect" },
  { key: "vocab-17", type: "vocab", word: "Improvise", meaning: "to create or perform without preparation", meaningKeywords: ["without preparation", "spontaneous", "adapt"], synonym: "extemporize", antonym: "rehearse" },
  { key: "vocab-18", type: "vocab", word: "Induce", meaning: "to bring about or persuade", meaningKeywords: ["cause", "bring about", "persuade"], synonym: "prompt", antonym: "prevent" },
  { key: "vocab-19", type: "vocab", word: "Integrity", meaning: "moral honesty and strong principles", meaningKeywords: ["honesty", "principles", "uprightness"], synonym: "honesty", antonym: "corruption" },
  { key: "vocab-20", type: "vocab", word: "Keen", meaning: "eager or sharp", meaningKeywords: ["eager", "sharp", "enthusiastic"], synonym: "eager", antonym: "apathetic" },
  { key: "vocab-21", type: "vocab", word: "Meticulous", meaning: "showing great attention to detail", meaningKeywords: ["careful", "detail", "thorough"], synonym: "thorough", antonym: "careless" },
  { key: "vocab-22", type: "vocab", word: "Noble", meaning: "having high moral qualities", meaningKeywords: ["moral", "honorable", "high"], synonym: "honorable", antonym: "ignoble" },
  { key: "vocab-23", type: "vocab", word: "Optimistic", meaning: "hopeful about the future", meaningKeywords: ["hopeful", "positive", "future"], synonym: "hopeful", antonym: "pessimistic" },
  { key: "vocab-24", type: "vocab", word: "Persevere", meaning: "to continue steadily despite difficulty", meaningKeywords: ["continue", "persist", "difficulty"], synonym: "persist", antonym: "quit" },
  { key: "vocab-25", type: "vocab", word: "Prudent", meaning: "acting with care and good judgment", meaningKeywords: ["careful", "wise", "judgment"], synonym: "wise", antonym: "reckless" },
  { key: "vocab-26", type: "vocab", word: "Resilient", meaning: "able to recover quickly", meaningKeywords: ["recover", "bounce back", "tough"], synonym: "adaptable", antonym: "fragile" },
  { key: "vocab-27", type: "vocab", word: "Resolve", meaning: "firm determination", meaningKeywords: ["determination", "firmness", "decision"], synonym: "determination", antonym: "indecision" },
  { key: "vocab-28", type: "vocab", word: "Sincere", meaning: "genuine and honest", meaningKeywords: ["genuine", "honest", "true"], synonym: "genuine", antonym: "insincere" },
  { key: "vocab-29", type: "vocab", word: "Steadfast", meaning: "firm and unwavering", meaningKeywords: ["firm", "constant", "unwavering"], synonym: "firm", antonym: "fickle" },
  { key: "vocab-30", type: "vocab", word: "Tactful", meaning: "sensitive in dealing with others", meaningKeywords: ["sensitive", "diplomatic", "careful"], synonym: "diplomatic", antonym: "rude" }
];

const wat = [
  { key: "wat-1", type: "wat", prompt: "Discipline", expectedPoints: ["self", "improvement", "consistency"], modelAnswer: "Discipline turns daily effort into dependable success." },
  { key: "wat-2", type: "wat", prompt: "Failure", expectedPoints: ["learn", "improve", "retry"], modelAnswer: "Failure teaches me to improve and try again with better planning." },
  { key: "wat-3", type: "wat", prompt: "Leader", expectedPoints: ["guide", "team", "responsibility"], modelAnswer: "A leader guides the team by taking responsibility first." },
  { key: "wat-4", type: "wat", prompt: "Obstacle", expectedPoints: ["solve", "effort", "progress"], modelAnswer: "Every obstacle invites a calm solution and stronger effort." },
  { key: "wat-5", type: "wat", prompt: "Friendship", expectedPoints: ["trust", "support", "respect"], modelAnswer: "True friendship grows through trust, respect, and timely support." },
  { key: "wat-6", type: "wat", prompt: "Time", expectedPoints: ["value", "plan", "use"], modelAnswer: "Time rewards those who plan and use it purposefully." },
  { key: "wat-7", type: "wat", prompt: "Courage", expectedPoints: ["act", "fear", "right"], modelAnswer: "Courage is acting rightly even when fear exists." },
  { key: "wat-8", type: "wat", prompt: "Team", expectedPoints: ["cooperate", "goal", "together"], modelAnswer: "A team reaches tough goals by cooperating with trust." },
  { key: "wat-9", type: "wat", prompt: "Responsibility", expectedPoints: ["duty", "ownership", "action"], modelAnswer: "Responsibility means owning the task and completing it well." },
  { key: "wat-10", type: "wat", prompt: "Service", expectedPoints: ["help", "society", "selfless"], modelAnswer: "Service gives purpose when skill is used for others." },
  { key: "wat-11", type: "wat", prompt: "Decision", expectedPoints: ["timely", "clear", "judgment"], modelAnswer: "A timely decision with sound judgment saves effort and time." },
  { key: "wat-12", type: "wat", prompt: "Patriotism", expectedPoints: ["nation", "duty", "conduct"], modelAnswer: "Patriotism is shown through duty, integrity, and national service." },
  { key: "wat-13", type: "wat", prompt: "Health", expectedPoints: ["fitness", "routine", "strength"], modelAnswer: "Good health is built by disciplined routine and balanced habits." },
  { key: "wat-14", type: "wat", prompt: "Study", expectedPoints: ["learn", "practice", "consistency"], modelAnswer: "Consistent study with practice creates reliable competence." },
  { key: "wat-15", type: "wat", prompt: "Pressure", expectedPoints: ["calm", "prioritize", "perform"], modelAnswer: "Pressure is handled best by calm priorities and steady action." },
  { key: "wat-16", type: "wat", prompt: "Change", expectedPoints: ["adapt", "learn", "grow"], modelAnswer: "Those who adapt to change grow stronger and wiser." },
  { key: "wat-17", type: "wat", prompt: "Respect", expectedPoints: ["earn", "conduct", "others"], modelAnswer: "Respect is earned by conduct that values others." },
  { key: "wat-18", type: "wat", prompt: "Adventure", expectedPoints: ["challenge", "learn", "spirit"], modelAnswer: "Adventure sharpens character when approached with preparation." },
  { key: "wat-19", type: "wat", prompt: "Training", expectedPoints: ["practice", "improvement", "skill"], modelAnswer: "Training converts repeated practice into confident skill." },
  { key: "wat-20", type: "wat", prompt: "Crisis", expectedPoints: ["calm", "respond", "lead"], modelAnswer: "In crisis, calm action inspires confidence in others." },
  { key: "wat-21", type: "wat", prompt: "Honesty", expectedPoints: ["truth", "trust", "character"], modelAnswer: "Honesty strengthens trust and builds lasting character." },
  { key: "wat-22", type: "wat", prompt: "Motivation", expectedPoints: ["purpose", "action", "effort"], modelAnswer: "Clear purpose keeps motivation alive through hard effort." },
  { key: "wat-23", type: "wat", prompt: "Competition", expectedPoints: ["improve", "fair", "perform"], modelAnswer: "Healthy competition pushes fair effort and better performance." },
  { key: "wat-24", type: "wat", prompt: "Duty", expectedPoints: ["serve", "complete", "commitment"], modelAnswer: "Duty is fulfilled by committed action, not excuses." },
  { key: "wat-25", type: "wat", prompt: "Confidence", expectedPoints: ["prepare", "believe", "perform"], modelAnswer: "Preparation is the strongest source of confidence." },
  { key: "wat-26", type: "wat", prompt: "Sacrifice", expectedPoints: ["larger good", "service", "commitment"], modelAnswer: "Meaningful sacrifice supports a larger purpose." },
  { key: "wat-27", type: "wat", prompt: "Problem", expectedPoints: ["analyze", "solve", "learn"], modelAnswer: "Every problem becomes smaller after calm analysis." },
  { key: "wat-28", type: "wat", prompt: "Initiative", expectedPoints: ["start", "act", "ownership"], modelAnswer: "Initiative begins when responsibility is accepted without waiting." },
  { key: "wat-29", type: "wat", prompt: "Focus", expectedPoints: ["priority", "avoid distraction", "goal"], modelAnswer: "Focus grows when priorities are chosen consciously." },
  { key: "wat-30", type: "wat", prompt: "Success", expectedPoints: ["effort", "discipline", "service"], modelAnswer: "Lasting success follows discipline, effort, and humility." }
];

const tat = [
  { key: "tat-1", type: "tat", prompt: "A student notices flood water entering nearby homes during heavy rain.", expectedPoints: ["notice", "organize", "help", "outcome"], modelAnswer: "Seeing flood water entering nearby homes, Ravi quickly alerted neighbors, moved children and elders to the community hall, and coordinated volunteers for food and dry clothes. He informed local authorities and helped prepare a list of urgent needs. By evening, all families were safe and relief distribution became orderly." },
  { key: "tat-2", type: "tat", prompt: "A young cadet sees two classmates arguing before an important event.", expectedPoints: ["mediate", "calm", "team", "outcome"], modelAnswer: "Before an important event, Aman noticed two classmates arguing and sensed the team was losing focus. He calmly separated them, heard both sides briefly, and reminded them of the common goal. He assigned immediate tasks so attention returned to preparation. The event went smoothly and the teammates resolved the issue afterward." },
  { key: "tat-3", type: "tat", prompt: "A village lacks a clean study space for children.", expectedPoints: ["initiative", "community", "organize", "result"], modelAnswer: "Priya saw village children struggling to study in noisy surroundings. She met the panchayat, collected unused books, and gathered volunteers to clean an empty room near the school. Within two weeks they turned it into a simple evening study center. Attendance improved and more students started preparing regularly." },
  { key: "tat-4", type: "tat", prompt: "A trek team loses its way as weather changes suddenly.", expectedPoints: ["calm", "lead", "safety", "result"], modelAnswer: "During a trek, clouds reduced visibility and the team began to panic. Arjun checked the map, halted unnecessary movement, and grouped everyone together. He assigned one member to signal, another to manage water, and led the team slowly toward a marked shelter. The team reached safety and later reviewed better preparation measures." },
  { key: "tat-5", type: "tat", prompt: "A college volunteer wants to improve blood donation participation.", expectedPoints: ["plan", "convince", "organize", "success"], modelAnswer: "Nisha wanted to improve participation in the college blood donation drive. She coordinated with doctors, made simple awareness posters, and addressed common fears through short talks. She also formed a volunteer desk for registration and support. Donations increased significantly and the drive became an annual event." },
  { key: "tat-6", type: "tat", prompt: "A friend is repeatedly underperforming due to poor routine.", expectedPoints: ["observe", "guide", "support", "improve"], modelAnswer: "Karan noticed his friend slipping academically because of an unplanned routine. He spoke to him respectfully, helped him create a realistic daily schedule, and studied with him for a week to build momentum. Gradually the friend regained confidence and improved his performance." },
  { key: "tat-7", type: "tat", prompt: "A junior in a sports camp feels left out and discouraged.", expectedPoints: ["include", "encourage", "train", "progress"], modelAnswer: "At a sports camp, Mehul saw a junior feeling isolated after repeated mistakes. He included him in warm-ups, demonstrated basic drills patiently, and praised small improvements. The junior regained confidence, practiced harder, and soon became an active team member." },
  { key: "tat-8", type: "tat", prompt: "A bus breaks down on the way to an exam center.", expectedPoints: ["calm", "coordinate", "alternative", "reach"], modelAnswer: "When the bus broke down, Sanya quickly checked the remaining time and calmed the worried students. She contacted a nearby taxi service, informed the exam center about the delay, and grouped students by route for faster travel. They reached on time with minimal confusion." },
  { key: "tat-9", type: "tat", prompt: "A college club is losing members due to poor engagement.", expectedPoints: ["analyze", "revive", "teamwork", "result"], modelAnswer: "Vikas observed declining participation in the college club and decided to act. He surveyed members, identified dull sessions as the main issue, and introduced practical workshops with clear responsibilities. Attendance improved and the club regained energy within a month." },
  { key: "tat-10", type: "tat", prompt: "A local park is dirty and unsafe for children.", expectedPoints: ["community action", "clean", "coordinate", "sustain"], modelAnswer: "Ritu saw that the local park had become dirty and unsafe for children. She mobilized residents for a cleanliness drive, requested municipal support for waste collection, and formed a weekend rota to maintain the area. The park became usable again and residents continued upkeep collectively." }
];

const srt = [
  { key: "srt-1", type: "srt", prompt: "You see a road accident on your way to an interview and there is no police nearby.", expectedPoints: ["help", "ambulance", "safety", "inform"], modelAnswer: "I would first ensure my own safety, move the injured away from immediate danger if possible, call ambulance and police, seek help from nearby people, and arrange quick transport if emergency response is delayed. After handing over the situation responsibly, I would inform the interview panel about the delay." },
  { key: "srt-2", type: "srt", prompt: "Your team misses a project deadline because one member did not finish his part.", expectedPoints: ["take ownership", "recover", "support", "prevent"], modelAnswer: "I would assess the unfinished work immediately, help complete the critical part with the team, and communicate a realistic recovery timeline. Later I would understand the cause, redistribute tasks better, and create progress checkpoints to prevent repetition." },
  { key: "srt-3", type: "srt", prompt: "During travel you realize your wallet is missing.", expectedPoints: ["calm", "verify", "block", "inform"], modelAnswer: "I would stay calm, retrace recent steps quickly, call to block cards, inform the nearest authority or transport desk, and secure my remaining essentials. I would then arrange temporary support through digital access or trusted contacts." },
  { key: "srt-4", type: "srt", prompt: "A classmate is using unfair means in an exam.", expectedPoints: ["discourage", "integrity", "report if needed"], modelAnswer: "I would not participate in it, discourage the classmate quietly if possible, and maintain my own integrity. If it continues in a way that affects fairness seriously, I would report it through the proper channel." },
  { key: "srt-5", type: "srt", prompt: "Your younger sibling wants to quit after repeated failure in a competition.", expectedPoints: ["encourage", "analyze", "plan", "improve"], modelAnswer: "I would first calm and encourage my sibling, analyze what went wrong, and help create a smaller practice plan with measurable targets. I would keep motivation high by focusing on improvement instead of only results." },
  { key: "srt-6", type: "srt", prompt: "You are made group leader but two seniors refuse to cooperate.", expectedPoints: ["respect", "communicate", "assign", "goal"], modelAnswer: "I would speak to them respectfully, clarify the common objective, and assign roles based on strengths rather than ego. By showing fairness and competence in action, I would work to earn their cooperation." },
  { key: "srt-7", type: "srt", prompt: "You are tired after a long day but a neighbor asks for urgent help.", expectedPoints: ["prioritize urgency", "help", "balance"], modelAnswer: "I would first judge the urgency. If the matter is important, I would help immediately or arrange help quickly instead of refusing. After the urgent need is addressed, I would return to my own rest or pending work." },
  { key: "srt-8", type: "srt", prompt: "Heavy rain disrupts an event you organized.", expectedPoints: ["contingency", "calm", "shift plan"], modelAnswer: "I would stay calm, move people and equipment to the safest available location, activate the backup plan, and inform all participants clearly. After stabilization, I would review what contingency improvements are needed." },
  { key: "srt-9", type: "srt", prompt: "You are given an unfamiliar task with very little time.", expectedPoints: ["learn fast", "prioritize", "seek clarity", "deliver"], modelAnswer: "I would clarify the expected output quickly, break the task into essentials, learn the minimum needed fast, and start execution without delay. If required, I would seek focused guidance while keeping delivery on time." },
  { key: "srt-10", type: "srt", prompt: "Your friend shares a rumor about another student and asks you to spread it.", expectedPoints: ["refuse", "verify", "responsible"], modelAnswer: "I would refuse to spread an unverified rumor, advise my friend to stop, and avoid harming someone unfairly. If the issue is serious, I would encourage proper verification through responsible means." }
];

const ppdt = [
  { key: "ppdt-1", type: "ppdt", prompt: "A young man standing near a stalled tractor while two villagers and a child watch from the roadside.", observations: "Likely rural setting, daytime, problem with transport or farming work, 4 characters, one central figure ready to act.", expectedPoints: ["observe", "initiative", "repair/help", "outcome"], modelAnswer: "Ramesh, a mechanically aware college student visiting his village, saw a stalled tractor blocking farm work. He quickly checked the fuel line, asked one villager to bring tools, and kept the child at a safe distance. After fixing the minor blockage, he helped restart the tractor and suggested a regular maintenance routine. Work resumed and the villagers appreciated the timely help." },
  { key: "ppdt-2", type: "ppdt", prompt: "A girl with a notebook speaking to three school children near a small building.", observations: "Possibly school or community center, daytime, educational setting, central female figure likely guiding others.", expectedPoints: ["lead", "teach", "organize", "progress"], modelAnswer: "Ananya noticed that younger children in her locality lacked guidance after school. She gathered them near the community building, assessed their basic problems, and started a daily one-hour study circle. Over a few weeks the children became more confident and regular in studies." },
  { key: "ppdt-3", type: "ppdt", prompt: "A group of youths gathered around a notice board while one person points at it.", observations: "Public place or campus, some announcement has created urgency, one person appears to be explaining the situation.", expectedPoints: ["clarify", "organize", "respond", "result"], modelAnswer: "Rahul saw confusion among students reading a sudden rescheduling notice. He read the details carefully, explained them to others, and divided tasks so everyone could update absent classmates and rearrange transport quickly. Because of his initiative, the group adapted without panic." },
  { key: "ppdt-4", type: "ppdt", prompt: "Two boys and an older man looking at a damaged bicycle beside a road.", observations: "Small roadside incident, no severe emergency visible, central opportunity is problem solving and responsibility.", expectedPoints: ["assist", "repair", "safe movement"], modelAnswer: "Seeing an elderly man worried about his damaged bicycle, Deepak stopped with his friend and examined the chain and pedal. They helped straighten the bent part temporarily, guided him away from traffic, and arranged a nearby repair shop. The man reached home safely and thanked them." },
  { key: "ppdt-5", type: "ppdt", prompt: "Several students sitting in a room while one stands near a chart paper.", observations: "Indoor discussion or briefing, likely teamwork or presentation, one person is leading planning.", expectedPoints: ["plan", "delegate", "lead", "complete"], modelAnswer: "Neeraj was leading his college team for a community awareness event. He outlined the objective on chart paper, delegated speaking, logistics, and poster work, and set a clear timeline. Because the planning was structured, the event was completed effectively and drew good public participation." },
  { key: "ppdt-6", type: "ppdt", prompt: "A person near a riverbank with two others carrying ropes.", observations: "Outdoor environment, possible rescue or recovery effort, coordinated action is required.", expectedPoints: ["safety", "teamwork", "organized action", "result"], modelAnswer: "After noticing a person stranded near the riverbank, Sameer quickly assessed the risk and stopped others from acting rashly. He used available ropes, assigned positions to two helpers, and contacted local rescue support. With coordinated action the stranded person was brought to safety." },
  { key: "ppdt-7", type: "ppdt", prompt: "A woman talking to villagers seated under a tree.", observations: "Rural discussion setting, likely awareness or problem-solving meeting, central figure is guiding the group.", expectedPoints: ["initiative", "community", "solution", "follow-up"], modelAnswer: "Meera learned that many villagers were facing water wastage due to poor storage habits. She organized a short meeting under the tree, explained simple conservation methods, and formed a small committee to implement them. Over time the village reduced wastage and improved water use." },
  { key: "ppdt-8", type: "ppdt", prompt: "A boy with a bag helping another person near a bus stop.", observations: "Travel setting, one person likely in difficulty, central figure appears to be assisting.", expectedPoints: ["help", "communicate", "resolve", "positive result"], modelAnswer: "At the bus stop, Aditya noticed a traveler confused about the route and carrying heavy luggage. He verified the correct bus timing, helped move the bags to a safer place, and guided the traveler to the right platform. The person boarded on time and avoided missing the journey." }
];

const CONTENT = { vocab, wat, tat, srt, ppdt };

module.exports = { CONTENT };
